CREATE TABLE IF NOT EXISTS `#__hwdlinks_link` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'The type of link: Content, URL, Alias, Empty',
  `title` VARCHAR(255) NOT NULL COMMENT 'The display title of the link',
  `alias` VARCHAR(400) NOT NULL COMMENT 'Alias',
  `link` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'The actually link the menu item refers to.',
  `document` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'Path to document',
  `menu` INT(11) NULL DEFAULT '0' COMMENT 'Menu item id',
  `article` INT(11) NULL DEFAULT '0' COMMENT 'Article id',
  `published` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'The published state of the menu link.',
  `parent_id` INT(10) UNSIGNED NOT NULL DEFAULT '1' COMMENT 'The parent menu item in the menu tree.',
  `level` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'The relative level in the tree.',
  `path` VARCHAR(1024) NULL DEFAULT NULL COMMENT 'The path',
  `lft` INT(11) NOT NULL DEFAULT '0' COMMENT 'Nested set lft.',
  `rgt` INT(11) NOT NULL DEFAULT '0' COMMENT 'Nested set rgt.',
  `created_by` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Modified by user id',
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'The time the link was modified.',
  `modified_by` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Modified by user id',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'The time the link was modified.',
  `browserNav` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'The click behaviour of the link.',
  `access` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'The access level required to view the menu item.',
  `image` VARCHAR(1024) NULL COMMENT 'The image of the menu item.',
  `alt` VARCHAR(255) NOT NULL DEFAULT '0' COMMENT 'The alt text of image when image is not available',
  `params` TEXT NULL COMMENT 'JSON encoded data for the menu item.',
  `language` CHAR(7) NOT NULL DEFAULT '0' COMMENT 'JSON encoded data for the menu item',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
